[devices.buds]
mac = "B8:7B:D4:19:2D:8D"
device_type = "buds"
battery_command = "$HOME/bin/pbpctrl show battery"

[devices.qc35]
mac = "AC:BF:71:09:BF:FD"
device_type = "bluetooth"

[devices.controller]
mac = "98:7A:14:C9:9A:90"
device_type = "bluetooth"

# [devices.mx]
# mac = "D5:E4:1B:10:D6:75"
# device_type = "bluetooth"
