theme = "oxocarbon"

[editor]
evil = true
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
scroll-lines = 15

[editor.search]
smart-case = true

[editor.whitespace]
render = "all"
characters = { space = "·", tab = "→" }

[editor.file-picker]
hidden = false
