[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yaml", "yml"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "sql"
scope = "source.sql"
file-types = ["sql"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "ruby"
scope = "source.ruby"
file-types = ["rb"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "html"
scope = "text.html.basic"
file-types = ["html", "htm"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "css"
scope = "source.css"
file-types = ["css"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "xml"
scope = "text.xml"
file-types = ["xml"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "vim"
scope = "source.vim"
file-types = ["vim"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "c"
scope = "source.c"
file-types = ["c", "h", "def"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs", "lalrpop"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
scope = "source.python"
file-types = ["py", "cconf", "cinc"]
indent = { tab-width = 4, unit = "    " }
