[env]
TERM = "xterm-256color"

[window.padding]
x = 2
y = 2

[scrolling]
history = 10000

[mouse]
hide_when_typing = true

[font]
size = 12.0

[font.normal]
family = "Comic Code"
style  = "Regular"

[font.bold]
family = "Comic Code"
style  = "Regular"

[font.italic]
family = "Comic Code"
style  = "Regular"

[colors.normal]
black   = '#282026'
red     = '#cf4f5f'
green   = '#2fa526'
yellow  = '#c48702'
blue    = '#379cf6'
magenta = '#b0648f'
cyan    = '#3fafcf'
white   = '#dfd0d5'

[colors.bright]
black   = '#554f4f'
red     = '#d24f7f'
green   = '#00b066'
yellow  = '#df8f6f'
blue    = '#029fff'
magenta = '#a6699f'
cyan    = '#4fafaf'
white   = '#908890'

[colors.cursor]
cursor = '#fd3333'
text   = '#15050f'

[colors.primary]
background = '#15050f'
foreground = '#dfd0d5'

[colors.selection]
background = '#293140'
text       = '#dfd0d5'

[cursor.style]
shape    = "Block"
blinking = "Never"

[[keyboard.bindings]]
key    = "C"
mods   = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key    = "V"
mods   = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key    = "Insert"
mods   = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key    = "R"
mods   = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key    = "Plus"
mods   = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key    = "Equals"
mods   = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key    = "Minus"
mods   = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key    = "Key0"
mods   = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key    = "N"
mods   = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key    = "O"
mods   = "Control|Shift"
action = "ToggleViMode"

[[keyboard.bindings]]
key    = "U"
mods   = "Control|Shift"
action = "ToggleViMode"
